apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumenhello
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: lumenhello-service
  template:
    metadata:
      labels:
        run: lumenhello-service
    spec:
      containers:
      - name: lumenhello-site
        image: aalvanh/get-started:part1
---
apiVersion: v1
kind: Service
metadata:
  name: lumenhello-point
  namespace: default
spec:
  type: LoadBalancer
  selector:
    run: lumenhello-service
  ports:
  - port: 3030
    targetPort: 3030
    nodePort: 30003